language: generic

compiler:
    - g++

sudo: required

dist: trusty

addons:
  apt:
    packages:
      - g++
      - gettext
      - intltool


before_script:
    - cd build
    - export PKG_CONFIG_PATH=/app/lib/pkgconfig:${PKG_CONFIG_PATH}
    - export LD_LIBRARY_PATH=/app/lib:${LD_LIBRARY_PATH}
    - git clone -b v8.4.2 --depth 1 https://github.com/jcupitt/libvips.git libvips
    - cd libvips
    - ./autogen.sh
    - FLAGS="-O2 -msse4.2 -ffast-math -ftree-vectorize" CFLAGS="${FLAGS}" CXXFLAGS="${FLAGS} -fpermissive" ./configure --prefix=/app --disable-gtk-doc --disable-gtk-doc-html --disable-introspection --enable-debug=no --without-python --without-magick --without-libwebp --enable-pyvips8=no --enable-shared=yes --enable-static=no
    - make -j2
    - sudo make install
    - cd ..
    - rm -rf libvips
    - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/app -DINSTALL_PREFIX=/app -DBUNDLED_LENSFUN=ON ..
    - make -j2
    - sudo make install
    - cd ..
    - sudo rm -fr PhotoFlow

script:
    - bash appimage/appimage.sh
